[package]
name = "stash-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "stash"
path = "src/main.rs"

[dependencies]
etude-core = { path = "../etude-core" }
etude-keep = { path = "../etude-keep" }

[dev-dependencies]
fixtures = { path = "../fixtures" }
